### ISSUE TITLE
Multiple Steam ID Error

### ISSUE THREAD

**Issue by cainanfoster** [komeg1/cs2res_fix#1]
When the program asks to specify which Steam ID to use, it shows two which aren't on my machine. Then, when I reopen the dir prompt, it generates another two. This happens every time you specify the directory. I'll just fuck around till I find which one.

![image](https://github.com/komeg1/cs2res_fix/assets/13905953/9337ee7e-b20f-4060-adf3-9dcabd5344ff)

**Comment by komeg1** [comment]
the IDs are the folder names in `../Steam/userdata/{steamid}` that contain `730` folder. Notice that these are just suffixes of the full steamid. just fixed the repetetive generation in 390e817e708f85bcc4b00a3ebdf7eae76ca2c753. thanks for the feedback :).
